# Relocatable package configuration. Requires CMake >= 3.24 for WHOLE_ARCHIVE.
include("${CMAKE_CURRENT_LIST_DIR}/MNNFeatures.cmake")
set(MNN_FOUND TRUE)
foreach(_mnn_component IN LISTS MNN_FIND_COMPONENTS)
  if(_mnn_component IN_LIST MNN_AVAILABLE_BACKENDS)
    set(MNN_${_mnn_component}_FOUND TRUE)
  else()
    set(MNN_${_mnn_component}_FOUND FALSE)
    if(MNN_FIND_REQUIRED_${_mnn_component})
      set(MNN_FOUND FALSE)
      set(MNN_NOT_FOUND_MESSAGE "Backend ${_mnn_component} is unavailable in profile ${MNN_PROFILE}")
      return()
    endif()
  endif()
endforeach()
if(TARGET MNN::MNN)
  return()
endif()
include(CMakeFindDependencyMacro)
if("cuda" IN_LIST MNN_AVAILABLE_BACKENDS)
  find_dependency(CUDAToolkit 12.8)
  if(CUDAToolkit_VERSION VERSION_GREATER_EQUAL 13)
    set(MNN_FOUND FALSE)
    set(MNN_NOT_FOUND_MESSAGE "This CUDA 12 package requires CUDA Toolkit >=12.8,<13")
    return()
  endif()
endif()
get_filename_component(_mnn_root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
option(MNN_USE_STATIC_LIBS "Link the prebuilt static MNN library" ON)
if(MNN_USE_STATIC_LIBS)
  if(WIN32)
    set(_mnn_library "${_mnn_root}/lib/MNN_static.lib")
  else()
    set(_mnn_library "${_mnn_root}/lib/libMNN.a")
  endif()
  add_library(MNN::Native STATIC IMPORTED)
  set_target_properties(MNN::Native PROPERTIES IMPORTED_LOCATION "${_mnn_library}")
else()
  add_library(MNN::Native SHARED IMPORTED)
  if(WIN32)
    set(_mnn_library "${_mnn_root}/lib/MNN.dll")
    set_target_properties(MNN::Native PROPERTIES
      IMPORTED_IMPLIB "${_mnn_root}/lib/MNN.lib"
      INTERFACE_COMPILE_DEFINITIONS USING_MNN_DLL)
  elseif(APPLE)
    set(_mnn_library "${_mnn_root}/lib/libMNN.dylib")
  else()
    set(_mnn_library "${_mnn_root}/lib/libMNN.so")
  endif()
  set_target_properties(MNN::Native PROPERTIES IMPORTED_LOCATION "${_mnn_library}")
endif()
if(NOT EXISTS "${_mnn_library}")
  message(FATAL_ERROR "Requested MNN library is not available: ${_mnn_library}")
endif()
set_target_properties(MNN::Native PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_mnn_root}/include")
add_library(MNN::MNN INTERFACE IMPORTED)
if(MNN_USE_STATIC_LIBS)
  set_property(TARGET MNN::MNN PROPERTY INTERFACE_LINK_LIBRARIES
    "$<LINK_LIBRARY:WHOLE_ARCHIVE,MNN::Native>")
  if(APPLE)
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES
      "-framework Foundation" "-framework Metal" "-framework CoreGraphics")
    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
      set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES "-framework UIKit")
    endif()
    if("coreml" IN_LIST MNN_AVAILABLE_BACKENDS)
      set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES
        "-framework CoreML" "-framework CoreVideo")
    endif()
  elseif(ANDROID)
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES log android m)
    if("opengl" IN_LIST MNN_AVAILABLE_BACKENDS)
      set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES GLESv3 EGL)
    endif()
  elseif(UNIX)
    include(CMakeFindDependencyMacro)
    find_dependency(Threads)
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES Threads::Threads ${CMAKE_DL_LIBS} m)
  endif()
else()
  set_property(TARGET MNN::MNN PROPERTY INTERFACE_LINK_LIBRARIES MNN::Native)
endif()
if("cuda" IN_LIST MNN_AVAILABLE_BACKENDS)
  if(UNIX)
    set(_mnn_cuda_dir "${_mnn_root}/lib")
    if(MNN_USE_STATIC_LIBS)
      string(APPEND _mnn_cuda_dir "/cuda-static")
    endif()
    if(NOT EXISTS "${_mnn_cuda_dir}/libMNN_Cuda_Main.so")
      message(FATAL_ERROR "Required MNN CUDA companion library is missing")
    endif()
    add_library(MNN::CudaMain SHARED IMPORTED)
    set_target_properties(MNN::CudaMain PROPERTIES
      IMPORTED_LOCATION "${_mnn_cuda_dir}/libMNN_Cuda_Main.so")
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES MNN::CudaMain)
  endif()
  set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES CUDA::cudart CUDA::cublas)
endif()
