# Relocatable package configuration. Requires CMake >= 3.24 for WHOLE_ARCHIVE.
if(TARGET MNN::MNN)
  return()
endif()
get_filename_component(_mnn_root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
option(MNN_USE_STATIC_LIBS "Link the prebuilt static MNN library" ON)
if(MNN_USE_STATIC_LIBS)
  if(WIN32)
    set(_mnn_library "${_mnn_root}/lib/MNN_static.lib")
  else()
    set(_mnn_library "${_mnn_root}/lib/libMNN.a")
  endif()
  add_library(MNN::Native STATIC IMPORTED)
  set_target_properties(MNN::Native PROPERTIES IMPORTED_LOCATION "${_mnn_library}")
else()
  add_library(MNN::Native SHARED IMPORTED)
  if(WIN32)
    set(_mnn_library "${_mnn_root}/lib/MNN.dll")
    set_target_properties(MNN::Native PROPERTIES
      IMPORTED_IMPLIB "${_mnn_root}/lib/MNN.lib"
      INTERFACE_COMPILE_DEFINITIONS USING_MNN_DLL)
  elseif(APPLE)
    set(_mnn_library "${_mnn_root}/lib/libMNN.dylib")
  else()
    set(_mnn_library "${_mnn_root}/lib/libMNN.so")
  endif()
  set_target_properties(MNN::Native PROPERTIES IMPORTED_LOCATION "${_mnn_library}")
endif()
if(NOT EXISTS "${_mnn_library}")
  message(FATAL_ERROR "Requested MNN library is not available: ${_mnn_library}")
endif()
set_target_properties(MNN::Native PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_mnn_root}/include")
add_library(MNN::MNN INTERFACE IMPORTED)
if(MNN_USE_STATIC_LIBS)
  set_property(TARGET MNN::MNN PROPERTY INTERFACE_LINK_LIBRARIES
    "$<LINK_LIBRARY:WHOLE_ARCHIVE,MNN::Native>")
  if(APPLE)
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES
      "-framework Foundation" "-framework Metal" "-framework CoreGraphics")
  elseif(ANDROID)
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES log android m)
  elseif(UNIX)
    include(CMakeFindDependencyMacro)
    find_dependency(Threads)
    set_property(TARGET MNN::MNN APPEND PROPERTY INTERFACE_LINK_LIBRARIES Threads::Threads ${CMAKE_DL_LIBS} m)
  endif()
else()
  set_property(TARGET MNN::MNN PROPERTY INTERFACE_LINK_LIBRARIES MNN::Native)
endif()
